image:
  repository: matthewkwong/k8s-cosign-wrapper
  pullPolicy: Always
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi
