apiVersion: v1
kind: Secret
metadata:
  name: k8s-cosign-wrapper-pub-key
  namespace: k8s-cosign-wrapper
type: Opaque
data:
  cosign.pub: |
    {{ .Files.Get "cosign.pub" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: k8s-cosign-wrapper-docker-config
  namespace: k8s-cosign-wrapper
type: Opaque
data:
  config.json: |
    {{ .Files.Get "docker_config.json" | b64enc }}
