apiVersion: v1
kind: Service
metadata:
  name: cosign
  namespace: k8s-cosign-wrapper
spec:
  selector:
    app.kubernetes.io/instance: cosign
    app.kubernetes.io/name: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
